spring:
    application:
        name: user-service
    profiles:
        active: dev
    cloud:
        config:
            enabled: false
    # config:
    #     import: optional:configserver:http://localhost:8888
server:
    port: 8888
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka
gateway:
    ip: 127.0.0.1
