apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2 # number of desired replicas
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: alger426/spring:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80 # port on which your Spring Boot app is running
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production" # set the active profile for your Spring Boot app
        # add more environment variables as needed
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
  - name: http
    port: 80 # external port to expose your service on
    targetPort: 80 # internal port on which your Spring Boot app is running