server:
    port: 8881
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
spring:
    application:
        name: map-service
    profiles:
        include: "dev"
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        generate-ddl: true
        defer-datasource-initialization: true
        properties:
            hibernate:
                format_sql: true
    sql:
        init:
            mode: always
            encoding: UTF-8
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type: trace
eureka:
    instance:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka
